# Generated by Django 5.2.5 on 2025-09-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name']},
        ),
    ]
